name: TMDB Lookup

on:
  workflow_dispatch:
    inputs:
      IMDB_ID:
        description: 'The IMDB ID for the content to lookup'
        required: true
        default: "550"
jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
      - name: Install httpie with pip
        run: python -m pip install httpie
      - name: Get the content
        run: http https://api.themoviedb.org/3/movie/${{ github.event.inputs.IMDB_ID }}?api_key=${{ secrets.TMDB_API_KEY }}
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Install httpie with apt
        run: apt install httpie
      - name: Get the content
        run: http https://api.themoviedb.org/3/movie/${{ github.event.inputs.IMDB_ID }}?api_key=${{ secrets.TMDB_API_KEY }}
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Get the content
        run: curl https://api.themoviedb.org/3/movie/${{ github.event.inputs.IMDB_ID }}?api_key=${{ secrets.TMDB_API_KEY }}
