name: TMDB Lookup

on:
  workflow_dispatch:
    inputs:
      IMDB_ID:
        description: 'The IMDB ID for the content to lookup'
        required: true
        default: "550"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Get the content
        run: curl -s https://api.themoviedb.org/3/movie/${{ github.event.inputs.IMDB_ID }}?api_key=${{ secrets.TMDB_API_KEY }} | jq .
